iris = load_iris()
x,y = iris.data,iris.target
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=42)
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
mlp = MLPClassifier(hidden_layer_sizes=(10,10),activation="relu",max_iter = 500,random_state=42)
mlp.fit(x_train,y_train)
y_pred = mlp.predict(x_test)
accuracy = accuracy_score(y_test,y_pred)
print(f"Accuratezza del modello: {accuracy:.2f}")
